#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 12:49:49 2021

@author: josephdobos
"""
from scipy.stats import poisson
import matplotlib as plt

##P(n = 153)
# p = poisson.pmf(153, 171)
# print(p)

def calc():
    total = 0
    blank = []
    lst = [153, 154, 155, 156, 157, 157, 159, 160, 161, 162, 163, 164, 165, 166, 167, 
           168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 
           182, 183, 184, 185, 186, 187, 188, 189]
    mu = 171
    for ele in lst:
        blank.append(poisson.pmf(ele, mu))
    for i in range(len(blank)):
        total += blank[i]
    print(total)

